### ISSUE TITLE
site doesn't build locally

### ISSUE THREAD

**Issue by rprakashg** [microsoft/aksworkshop#34]
I forked this repo with the intention of adding some content. I'm trying to build/run locally and the site doesn't seem to build

```sh
make build-run
docker build -t azch/aks-site:latest -f Dockerfile .
Sending build context to Docker daemon  56.34MB
Step 1/8 : FROM jekyll/builder AS build
 ---> 4605d94a6b36
Step 2/8 : WORKDIR /src/app
 ---> Using cache
 ---> 68e9fbcc3244
Step 3/8 : COPY . .
 ---> Using cache
 ---> b98c900dfb3e
Step 4/8 : RUN mkdir _site && mkdir .jekyll-cache &&     jekyll build --future
 ---> Running in 71d41bca2804
ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-linux-musl]
Configuration file: /src/app/_config.yml
                    ------------------------------------------------
      Jekyll 4.0.0   Please append `--trace` to the `build` command
                     for any additional information or backtrace.
                    ------------------------------------------------
The command '/bin/sh -c mkdir _site && mkdir .jekyll-cache &&     jekyll build --future' returned a non-zero code: 1
make: *** [build-run] Error 1

```

**Comment by rprakashg** [comment]
After adding the --trace to jekyll build command, increased the disk image size in docker desktop preferences and life is good

```sh
/usr/local/lib/ruby/2.6.0/fileutils.rb:239:in `mkdir': No space left on device @ dir_s_mkdir - /src/app/.jekyll-cache/Jekyll (Errno::ENOSPC)
	from /usr/local/lib/ruby/2.6.0/fileutils.rb:239:in `fu_mkdir'
	from /usr/local/lib/ruby/2.6.0/fileutils.rb:217:in `block (2 levels) in mkdir_p'
	from /usr/local/lib/ruby/2.6.0/fileutils.rb:215:in `reverse_each'
	from /usr/local/lib/ruby/2.6.0/fileutils.rb:215:in `block in mkdir_p'
	from /usr/local/lib/ruby/2.6.0/fileutils.rb:200:in `each'
	from /usr/local/lib/ruby/2.6.0/fileutils.rb:200:in `mkdir_p'
	from /usr/gem/gems/jekyll-4.0.0/lib/jekyll/cache.rb:184:in `dump'
	from /usr/gem/gems/jekyll-4.0.0/lib/jekyll/cache.rb:101:in `[]='
	from /usr/gem/gems/jekyll-4.0.0/lib/jekyll/cache.rb:45:in `clear_if_config_changed'
	from /usr/gem/gems/jekyll-4.0.0/lib/jekyll/site.rb:113:in `reset'
	from /usr/gem/gems/jekyll-4.0.0/lib/jekyll/site.rb:33:in `initialize'
	from /usr/gem/gems/jekyll-4.0.0/lib/jekyll/commands/build.rb:30:in `new'
	from /usr/gem/gems/jekyll-4.0.0/lib/jekyll/commands/build.rb:30:in `process'
	from /usr/gem/gems/jekyll-4.0.0/lib/jekyll/command.rb:89:in `block in process_with_graceful_fail'
	from /usr/gem/gems/jekyll-4.0.0/lib/jekyll/command.rb:89:in `each'
	from /usr/gem/gems/jekyll-4.0.0/lib/jekyll/command.rb:89:in `process_with_graceful_fail'
	from /usr/gem/gems/jekyll-4.0.0/lib/jekyll/commands/build.rb:18:in `block (2 levels) in init_with_program'
	from /usr/gem/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
	from /usr/gem/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
	from /usr/gem/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
	from /usr/gem/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
	from /usr/gem/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
	from /usr/gem/gems/jekyll-4.0.0/exe/jekyll:15:in `<top (required)>'
	from /usr/gem/bin/jekyll:23:in `load'
	from /usr/gem/bin/jekyll:23:in `<main>'
``
